woowacourse-teams/2024-touroot

.github/workflows/be-dev-ci-cd.yml
- deploy.sh을 활용하지 않도록 결정
- 명령어를 Github Actions workflow에서 직접 실행
- Github Actions workflow 파일 이름 변경
=> [Fix] - CD deploy.sh 실행 경로 수정

.github/workflows/be-cd-dev.yml, .github/workflows/be-ci.yml, .github/workflows/be-pull-request.yml
- 모든 branch 로 PR 생성 시 빌드 및 테스트 하도록 github action workflow 작성
- 빌드 및 테스트 실패시 PR을 merge 할 수 없도록 branch protection rule 설정
- 테스트 결과를 PR comment로 남기도록 yml 작성
- 테스트가 실패하는 코드에 리뷰를 남기도록 yml 작성
yml 파일 이름 변경
- `be-pull-request.yml` -> `be-ci.yml`
- `be-dev-ci-cd.yml` -> `be-cd-dev.yml`
=> [Feature] - PR을 생성 할 때 빌드 및 테스트 하는 CI Workflow 추가

backend/src/main/java/woowacourse/touroot/TourootApplication.java, backend/src/main/java/woowacourse/touroot/entity/BaseEntity.java, backend/src/main/java/woowacourse/touroot/place/domain/Place.java, backend/src/main/java/woowacourse/touroot/travelogue/day/domain/TravelogueDay.java, backend/src/main/java/woowacourse/touroot/travelogue/day/dto/TravelogueDayResponse.java, backend/src/main/java/woowacourse/touroot/travelogue/day/repository/TravelogueDayRepository.java, backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java, backend/src/main/java/woowacourse/touroot/travelogue/dto/TravelogueResponse.java, backend/src/main/java/woowacourse/touroot/travelogue/photo/domain/TraveloguePhoto.java, backend/src/main/java/woowacourse/touroot/travelogue/photo/repository/TraveloguePhotoRepository.java, backend/src/main/java/woowacourse/touroot/travelogue/place/domain/TraveloguePlace.java, backend/src/main/java/woowacourse/touroot/travelogue/place/dto/TraveloguePlaceResponse.java, backend/src/main/java/woowacourse/touroot/travelogue/place/repsitory/TraveloguePlaceRepository.java, backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueService.java, backend/src/main/java/woowacourse/touroot/travelogueday/dto/TravelogueDayResponse.java
- 패키지 구조 리팩토링
- BaseEntity 설계 및 구현
=> [Feature] - JPA Auditing을 위한 BaseEntity 생성

backend/src/main/java/woowacourse/touroot/global/exception/GlobalExceptionHandler.java, backend/src/main/java/woowacourse/touroot/global/exception/dto/ErrorResponse.java, backend/src/main/java/woowacourse/touroot/global/exception/dto/ExceptionResponse.java, backend/src/main/java/woowacourse/touroot/travelplan/controller/TravelPlanController.java, backend/src/main/java/woowacourse/touroot/travelplan/domain/TravelPlanDay.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanDayCreateRequest.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanLocationCreateRequest.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanPlaceCreateRequest.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/request/TravelPlanCreateRequest.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanCreateResponse.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanDayResponse.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanLocationResponse.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanPlaceResponse.java, backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanResponse.java, backend/src/main/java/woowacourse/touroot/travelplan/service/TravelPlanService.java, backend/src/test/java/woowacourse/touroot/travelplan/controller/TravelPlanControllerTest.java, backend/src/test/java/woowacourse/touroot/travelplan/service/TravelPlanServiceTest.java, backend/src/test/java/woowacourse/touroot/utils/TestFixture.java
- Swagger label 표시 수정 (여행기 -> 여행계획)
- 여행 계획 상세 조회 API 구현
=> [Feature] - 여행 계획 상세 조회 API 구현

.github/workflows/be-ci.yml
- CI 액션에 전달하는 xml 파일 경로 수정
- CI `publish-unit-test-result-action` 버전 업그레이드 (v1 -> v2)
- CI `publish-unit-test-result-action` 의 동시 read/write 요청 시간 증가 및 재시도 대기 시간 증가
- PR merge 조건으로 `publish-unit-test-result-action` 성공 여부 삭제
- 테스트 및 빌드 실패 시 `build` 액션이 실패하기 때문에 `build` 액션 성공 여부만 PR merge 조건에 넣었습니다.
=> [Fix] - CI xml 파일 미인식 문제 및 요청 초과로 인한 액션 실패 해결

backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePlaceRequest.java, backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePositionRequest.java, backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TraveloguePlaceResponse.java, backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TraveloguePositionResponse.java, backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java, backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueTestFixture.java, backend/src/test/java/woowacourse/touroot/travelogue/helper/TravelogueTestHelper.java, backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePhotoServiceTest.java, backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePlaceServiceTest.java
-  프론트엔드 파트의 요청에 맞춰 Location 속성의 이름을 Position으로 변경
=> [Refactor] - 여행기 응답 DTO 속성 이름 변경

backend/src/main/java/woowacourse/touroot/global/config/WebConfig.java
=> [Feature] - FE develop CORS 처리

backend/src/main/java/woowacourse/touroot/image/infrastructure/AwsS3Provider.java
- S3에 이미지 업로드 요청시 ContentType을 원본 파일의 ContentType으로 설정함으로서 이미지가 다운로드 되는 버그 해결
=> [Fix] - 업로드한 이미지 url에 접속하면 이미지를 열지 않고 다운로드 받는 버그 해결

backend/src/main/java/woowacourse/touroot/global/exception/GlobalExceptionHandler.java, backend/src/main/resources/application.yml
- 파일 업로드 용량 조정
- 개별 파일 5mb까지 허용
- 총 요청 50mb까지 허용
- 파일 업로드 예외 전역 처리기에서 처리하도록 수정
=> [Fix] - 업로드 이미지 용량 조정

backend/src/main/java/kr/touroot/authentication/controller/LoginController.java, backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/resources/application.yml
- 로그인 HTTP Method GET으로 변경 
로컬에서의 Oauth로그인을 원활히 실행하기 위해 인가가 구현될때까지 임시적으로 GET처리합니다.
인가 쪽 구현이 굳어지면 명세가 다시 바뀌어야 합니다. 
- Login Api는 accessToken이 계속 바뀜으로 멱등하지 않음
- 서버 상태를 바꾸기에 POST가 적절(회원가입도 하기 때문)
떼껄룩에 적어놓을게요. 인가쪽 구현이 완료되면 명세 다시 수정겠습니다.
=> [Feature] - 로그인 명세 수정 개선

backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/java/kr/touroot/global/auth/MemberAuthMethodArgumentResolver.java, backend/src/main/java/kr/touroot/global/auth/dto/HttpRequestInfo.java, backend/src/main/java/kr/touroot/global/auth/dto/MemberAuth.java, backend/src/main/java/kr/touroot/global/exception/ForbiddenException.java, backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java, backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java, backend/src/main/java/kr/touroot/travelplan/dto/request/TravelPlanCreateRequest.java, backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java, backend/src/main/resources/application.yml, backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java, backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java, backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java, backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
- 여행 계획 작성 시 작성자 기록 추가
- 여행 계획 조회 시 작성자만 조회 가능하게 추가
=> [Feature] - 여행 계획 도메인쪽 인가 적용

backend/build.gradle, backend/src/main/java/kr/touroot/authentication/infrastructure/JwtTokenProvider.java, backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/java/kr/touroot/global/auth/MemberAuthMethodArgumentResolver.java, backend/src/main/java/kr/touroot/global/auth/dto/HttpRequestInfo.java, backend/src/main/java/kr/touroot/global/auth/dto/MemberAuth.java, backend/src/main/java/kr/touroot/global/exception/UnauthorizedException.java, backend/src/main/java/kr/touroot/member/domain/Member.java, backend/src/main/java/kr/touroot/member/service/MemberService.java, backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java, backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java, backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java, backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java, backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueFixture.java, backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
- 패키지 구조 변경
- 인증된 사용자(로그인 한 사용자)만 여행기를 작성할 수 있도록 리팩토링
- 사용자 서비스(MemberService) 구현
- 변경된 엔티티에 맞춰 여행기 관련 테스트에 사용자(작성자) 정보 추가
=> [Feature] - 로그인 한 사용자만 여행기를 작성할 수 있도록 리팩토링

backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java, backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePhotoRequest.java, backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java, backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java, backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java, backend/src/main/resources/application.yml, backend/src/test/java/kr/touroot/image/infrastructure/AwsS3ProviderTest.java, backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java, backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueFixture.java, backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePhotoFixture.java, backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java, backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java, backend/src/test/resources/application-test.yml
- Image를 임시 디렉토리로 업로드하도록 수정
- S3 임시 디렉토리 수명주기 설정
- 영구 디렉토리로 복사 기능 구현
- 테스트 Fixture의 url 변경
- 현재 수명 주기가 제대로 적용됐는지 확인하기 위해 우선 1일로 설정해놓았습니다. 이후 확인이 완료되면 적절한 일수로 수정해야 할 것 같습니다.
- PhotoService에서 AwsS3Provider를 호출하는데 인증이 필요해서 Mock을 추가했습니다.
=> [Feature] - 사용하지 않는 S3 이미지 관리 기능 구현

backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java, backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java, backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
- 썸네일 저장 시 S3의 영구 이미지 폴더로 복사 기능 구현
- url 파싱 오류 수정
=> [Fix] - 썸네일 이미지 S3 영구 폴더 복사 기능 구현

frontend/src/assets/svg/index.ts, frontend/src/components/common/Icon/svg-icons.json, frontend/src/components/common/Input/Input.styled.ts, frontend/src/components/common/Input/Input.tsx, frontend/src/components/common/Modal/Modal.stories.tsx, frontend/src/components/common/Modal/Modal.style.ts, frontend/src/components/common/Modal/Modal.tsx, frontend/src/components/common/Modal/ModalBody/ModalBody.styled.ts, frontend/src/components/common/Modal/ModalBody/ModalBody.tsx, frontend/src/components/common/Modal/ModalFooter/ModalFooter.styled.ts, frontend/src/components/common/Modal/ModalFooter/ModalFooter.tsx, frontend/src/components/common/Modal/ModalHeader/ModalHeader.styled.ts, frontend/src/components/common/Modal/ModalHeader/ModalHeader.tsx, frontend/src/contexts/ModalProvider.tsx, frontend/src/hooks/useModalControl.ts, frontend/src/hooks/usePressESC.ts
- Modal 컴포넌트 구현
- ModalHeader, ModalBody, ModalFooter로 구성(compound pattern)
- Modal 동작과 관련된 hook 추가(useModalControl, usePressESC)
- Modal 스토리북 내 추가
<div align="center">
</div>
- DeleteModal이랑 ShareModal 관련 스토리북에 추가해두었으니 보고 작업하시면 더 편할거 같습니다~
- 뚜리 img의 경우 아이콘이 제대로 보이지 않는 이슈가 있습니다 ㅜㅜ
- emotion에서 css prop이 동작하지 않는 이슈가 있어 png로 대체하긴 했는데, url로 따로 추가해두었으니 img 형태로 사용하셔서 사이즈 조절하시면 될듯 합니다!
=> [Feature] - 모달 컴포넌트 구현

backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java, backend/src/main/java/kr/touroot/travelplan/dto/request/TravelPlanCreateRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanCreateResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPlaceResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPositionResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanResponse.java, backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanRepository.java, backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java, backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java, backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java, backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java, backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java, backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
-  여행 계획 엔티티에 공유 키 필드 추가
- UUID 생성 서비스 추가
- 공유 키로 여행 계획 조회 API 추가
=> [Feature] - 여행 계획 공유 기능 구현

frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx, frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx, frontend/src/contexts/TravelTransformDetailProvider.tsx
- 페이지를 벗어나면 transformDetail를 null로 변경
https://github.com/user-attachments/assets/c6952701-d5ea-4954-a2b2-00a313274cb2
https://github.com/user-attachments/assets/8261e313-3d2c-4fca-9a12-92c631455586
x
=> [Fix] - 여행 전환 후 다른 페이지에서 다시 등록 페이지로 접근 시 데이터가 남아있는 문제 해결

backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java, backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
- uuId가 binary로 전환되도록 컬럼 데피니션 삭제
- uuid 널 검증 및 테스트 추가
떼껄룩 참고
=> [Fix] - 여행 계획 UUID 하이버네이트 매핑 타입과 같도록 수정

backend/src/main/java/kr/touroot/authentication/controller/LoginController.java, backend/src/main/java/kr/touroot/authentication/infrastructure/KakaoOauthClient.java, backend/src/main/java/kr/touroot/authentication/infrastructure/KakaoOauthProvider.java, backend/src/main/java/kr/touroot/authentication/service/LoginService.java, backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/resources/application.yml, backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java, backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
- 쿼리파라미터로 인코딩된 redirectUri를 받도록 수정
- 쿼리파라미터의 디폴트 값을 활용하여 백엔드 로컬에서도 지금까지와 동일한 방식으로 로그인을 테스트 할 수 있습니다.
- 다만 로그인 같은 경우 현재 저희의 로직이라면 HTTP METHOD post가 맞는 것 같습니다.
- 백엔드 로컬에서의 로그인 확인을 포기하고 post로 명세를 수정하는 것이 좋을 지 현행처럼 get으로 둘지 고민이에요
- 의견 주시면 감사링
=> [Feature] - 로그인 명세 수정

frontend/src/components/pages/main/MainPage.tsx, frontend/src/components/pages/main/TravelogueCard/skeleton/TravelogueCardSkeleton.stories.tsx, frontend/src/components/pages/main/TravelogueCard/skeleton/TravelogueCardSkeleton.styled.ts, frontend/src/components/pages/main/TravelogueCard/skeleton/TravelogueCardSkeleton.tsx, frontend/src/styles/tokens/colors.ts
- 메인페이지 skeleton 작업
-  디자인 토큰에 shimmer 색상 추가
https://github.com/user-attachments/assets/fea0d5b3-1486-48d8-8ada-8707efdd1bf0
- 한번에 skeleton 5개 불러오도록 했습니다
=> [Feature] - 메인페이지 skeleton 작업

frontend/src/components/common/Header/Header.tsx, frontend/src/components/pages/login/KakaoCallbackPage.tsx, frontend/src/constants/endpoint.ts, frontend/src/constants/queryKey.ts, frontend/src/contexts/UserProvider.tsx, frontend/src/queries/useUserProfile.ts, frontend/src/types/domain/user.ts
- user 컨텍스트에 access token만 담는다.
- `nickname`, `profileImageUrl`은 api에서 가져온다.
- Drawer에서 로그인/로그아웃 버튼 로그아웃으로만 나오는 이슈 수정한다.
- 로그아웃 구현
- 로그아웃은 로컬스토리지에서 accessToken 지우는것으로 일단 구현해놨습니다
=> [Feature] - user 컨텍스트에 access token만 담도록 수정 & 로그인/로그아웃 버튼 수정

backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java, backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java, backend/src/main/java/kr/touroot/travelogue/domain/TravelogueDay.java, backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePhoto.java, backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java, backend/src/main/java/kr/touroot/travelogue/repository/TravelogueDayRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePlaceRepository.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueDayService.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java, backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java, backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java, backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java, backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanDayRepository.java, backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanPlaceRepository.java, backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java, backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java, backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java, backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java, backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
- 여행기, 여행 계획 soft delete 구현
- 없는 여행기, 여행 계획 삭제 시 400 예외를 발생시키는 기능 구현
- 작성자가 아닌 사용자가 삭제 시 403 예외를 발생시키는 기능 구현 
앞으로 트랜잭션 내에서만 외래키 제약 조건이 활성화 됩니다.
단일 데이터 삭제 시, soft delet로 인해 DB 단에서는 제약 조건이 터지지 않기 때문에 어플리케이션 레벨에서 잘 신경 써 주셔야 합니다.
S3 이미지 삭제는 좀 더 이야기 해 보아야 할 것 같습니다.
=> [Feature] - 삭제 API 구현

backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
- JwtAuthFilter에서 Bearer로 인증 헤더 split할 때 발생하는 오류 수정
=> [Fix] - JwtAuthFilter Authorization Header 파싱 오류 수정

backend/build.gradle, backend/src/main/java/kr/touroot/TourootApplication.java, backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/java/kr/touroot/tag/TagController.java, backend/src/main/java/kr/touroot/tag/cache/CacheConfig.java, backend/src/main/java/kr/touroot/tag/domain/Tag.java, backend/src/main/java/kr/touroot/tag/dto/TagCreateRequest.java, backend/src/main/java/kr/touroot/tag/dto/TagResponse.java, backend/src/main/java/kr/touroot/tag/repository/TagRepository.java, backend/src/main/java/kr/touroot/tag/service/TagService.java, backend/src/test/java/kr/touroot/tag/TagControllerTest.java, backend/src/test/java/kr/touroot/tag/fixture/TagFixture.java, backend/src/test/java/kr/touroot/tag/helper/TagTestHelper.java, backend/src/test/java/kr/touroot/tag/service/TagServiceTest.java
- 태그 Entity 생성
- 태그 생성 API
- 태그 조회 API
=> [Feature] - 태그 생성 및 조회 API 작성

backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java, backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePositionResponse.java, backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java, backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanDayResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPlaceResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPositionResponse.java, backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java, backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java, backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java, backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java, backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
- 여행기 하위 도메인 (날짜, 장소) 조회 시 id값도 반환하도록 명세 수정
- 여행 계획 하위 도메인 (날짜, 장소) 조회 시 id값도 반환하도록 명세 수정
- 오늘 날짜로 시작하는 여행 계획 도메인 생성 안되는 문제 해결
=> [Feature] - 여행 계획, 여행기 하위 도메인 조회 명세 변경

backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java, backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java, backend/src/test/java/kr/touroot/authentication/fixture/MemberFixture.java, backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java, backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java, backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
- `TravelogueResponse`에 `authorProfileImageUrl` 추가
=> [Refactor] - 메인 페이지 여행기 목록 응답에 사용자 프로필 사진 URL 추가

backend/src/main/java/kr/touroot/authentication/dto/response/LoginResponse.java, backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java, backend/src/main/java/kr/touroot/member/dto/request/MemberRequest.java
- 500 에러 응답 시 스택 트레이스도 출력하도록 변경
- Swagger 문서에서 프로필 이미지 url 예시 변경
=> [Feature] - 예외 로깅 시 InternalServerError 는 스택 트레이스도 같이 로깅하도록 변경

backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
- 엔티티의 description 필드 컬럼 명세 수정
=> [Fix] - 장소 설명이 255자를 넘어가는 여행기, 여행 계획이 저장 되지 않는 오류 수정

backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
- 내부 서버 에러 로깅 시 스택 트레이스가 제대로 로깅되도록 구현
=> [Fix] - InternalServerError 로깅 시 예외 스택 트레이스가 제대로 로깅되지 않는 문제 해결

frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx, frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx, frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx, frontend/src/hooks/useLeadingDebounce.ts
- 삭제 요청을 여러번 하지 못하도록 디바운싱 구현
- 등록 요청을 여러번 하지 못하도록 디바운싱 구현
=> [Fix] - 삭제 및 등록 시 여러번 요청하지 못하게 수정

frontend/src/apis/client.ts, frontend/src/apis/interceptor.ts, frontend/src/components/common/Header/Header.tsx, frontend/src/components/pages/login/KakaoCallbackPage.tsx, frontend/src/constants/endpoint.ts, frontend/src/types/domain/user.ts
- 서버로 부터 받은 refresh token을 로컬 스토리지에 저장
- access token이 만료 시 access token 재발급 로직 추가
- 리프레시 토큰이 만료될 경우 로그인 페이지로 리다이렉팅 하는 로직 추가
x
- AuthTokenResponse에 refreshToken 필드를 추가했습니다.
- 많은 이슈들이 있었는데 백로그에 기록해두었습니다.
- 인증 & 인가 관련해서도 tech log에 추가해두었으니 참고하시면 좋을듯해요~!
=> [Feature] - refresh token 클라이언트 내 적용

frontend/src/components/common/Tab/Tab.tsx, frontend/src/components/pages/my/MyPage.tsx, frontend/src/components/pages/travelogueDetail/Thumbnail/Thumbnail.styled.ts, frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.stories.tsx, frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.styled.ts, frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.tsx, frontend/src/constants/storage.ts, frontend/src/queries/useDeleteTravelogue.ts
- 여행지 사진에서 캐러셀이 아닌 이미지가 한장일 때 image error 처리 누락된 부분 추가
- 여행기 상세보기 페이지에서 썸네일 이미지가 가운데가 아닌 윗부분에 맞춰지게 되있던것 수정
1. tab을 선택하고 새로고침해도 선택된 tab이 유지되어야함
2. 하지만 다른 페이지로 이동할 경우  첫번 째 tab이 선택되어있어야함
3. 내 여행기를 삭제하고 마이페이지로 돌아갈 경우에는 마이페이지의 tab은 두번째 탭 (내 여행기) 이 선택되어있어함
-  그 이후 동작은 1~3 반복
많은 방법을 시도했봤지만, 결국 storage key를 1개로 유지하며 위 1~3 동작을 깔끔한 코드로 구현하기 어렵다고봤습니다.
MyPage의 Tab은 로컬스토리지에서 따로 관리하여 해결했습니다
=> Fix - image error 처리 누락, 여행기 삭제시 마이페이지로 넘어갈 때 tab 초기값 수정 , 여행기 썸네일

backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java, backend/src/main/java/kr/touroot/travelogue/domain/TravelogueLike.java, backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueLikeResponse.java, backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java, backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueSimpleResponse.java, backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java, backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java, backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java, backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueLikeServiceTest.java
- 좋아요 기능 구현
- 좋아요 취소 기능 구현
- 여행기 조회 시 응답에 좋아요 수, 사용자의 좋아요 여부 추가
- 메인 페이지에서 여행기 조회 시 응답에 좋아요 수 추가
- 좋아요와 좋아요 취소 기능은 반복 요청 시에도 정상적으로 응답합니다. 이는 인스타그램의 게시글 좋아요 기능에서 착안했습니다. 인스타그램에서 게시글 사진을 연속으로 더블 클릭해도 좋아요 상태가 유지되는 것처럼 구현했습니다.
- 프론트엔드 팀과의 논의 결과, 좋아요와 좋아요 취소 요청 시 동시성을 고려하여 응답에 `isLiked`와 `likeCount`를 포함하기로 했습니다. 다만, 좋아요 숫자의 정확성에 대해서는 추가적인 논의가 필요합니다. 이 부분은 전체 회의에서 더 깊이 있게 다루면 좋을 것 같습니다. 자세한 내용은 떼껄룩 문서를 참고해 주세요.
- 여행기 상세 조회 시 로그인/비로그인 사용자에 따라 다른 로직이 실행되어야 합니다. 너무 오래 고민하는 것 같아 일단은 오버로딩으로 구현했지만, 코드가 많이 복잡하다고 느껴집니다. 더 나은 방법을 계속 고민 중이니, 좋은 아이디어가 있으면 공유해 주시기 바랍니다.
=> [Feature] - 좋아요 기능 구현

frontend/src/components/common/MultiImageUpload/MultiImageUpload.stories.tsx, frontend/src/components/common/MultiImageUpload/MultiImageUpload.styled.ts, frontend/src/components/common/MultiImageUpload/MultiImageUpload.tsx, frontend/src/components/common/Spinner/Spinner.stories.tsx, frontend/src/components/common/Spinner/Spinner.styled.ts, frontend/src/components/common/Spinner/Spinner.tsx, frontend/src/components/common/Spinner/Spinner.type.ts, frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.constants.ts, frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx, frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
- Spinner 내 variants 및 size prop 추가 및 리팩터링
- 스토리북 추가 완료!
- MultiImageUpload 컴포넌트 내 image upload 중일 시 spinner를 렌더링 시키도록 변경 
- TravelogueMultiImageUpload 내 로딩 처리 완료
- 각 이미지 파일에 대한 개별 로딩 상태 관리 구현
- 업로드 요청 시작 시 해당 이미지의 로딩 상태를 true로 설정
- 업로드 완료 또는 실패 시 로딩 상태를 false로 변경
https://github.com/user-attachments/assets/cd505ce6-229a-4e17-be78-4de5e2ede881
- Spinner 컴포넌트 확인해주시면 좋을거 같슴다
- MultiImageUpload 스토리북 내에서 렉걸리던데, 그냥 스토리 지워버릴까 고민되는 부분입니다,,
=> [Feature] - 여행기 장소 이미지 업로드 중일 경우, spinner를 보여주도록 리팩터링

backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanDayRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceTodoRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPositionRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanRequest.java, backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java, backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java, backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
-  PUT Method 매핑
-  엔티티 수정 기능 구현
- 이미 여행을 간 상태에서 수정을 할 수 있다고 생각해 지난 날짜 검증은 하지 않았습니다.
- 일단 갖고 있는 하위 엔티티들을 전부 삭제 후 다시 생성하는 식으로 구현했기 때문에 Todo의 checked를 알아야 합니다. 따라서 TODO 요청 객체에서 해당 boolean 값도 받도록 수정했습니다.
- 여행 계획 관련 createRequest 객체들을 재사용하는 편이 깔끔할 것 같아 create를 빼고 사용하도록 수정했습니다.
=> [Feature] - 여행 계획 수정 기능 구현

backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java
- `TraveloguePlace`와 `TraveloguePhoto` 삭제 쿼리의 테이블 alias 중복 제거
=> [Fix] - 삭제 기능 쿼리 문제 해결

backend/Dockerfile, backend/src/main/java/kr/touroot/global/config/SwaggerConfig.java, backend/src/main/resources/application.yml, backend/src/main/resources/logback-spring.xml
- Spring boot Prod 분리
- prod 프로필에서 swagger 비활성화
- Dockerfile에서 프로필 지정 부분 제거 및 docker-compose.yml 수정
- Dockerfile에서 profile 지정하는 부분 변경하고 각 인스턴스의 docker-compose.yml에 프로필 지정 환경 변수 추가했습니다.
- @hangillee prod용 CI/CD에서 keystore 생성 시 `PROD_KEY_STORE` secret 사용해서 생성해야 올바른 인증서로 생성됩니다.
=> [Feature] - Spring boot Prod 프로필 분리

backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePlaceRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/TravelogueTagRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueDayQueryRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueDayQueryRepositoryImpl.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePhotoQueryRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePhotoQueryRepositoryImpl.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePlaceQueryRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePlaceQueryRepositoryImpl.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueTagQueryRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueTagQueryRepositoryImpl.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueDayService.java, backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java, backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java, backend/src/test/java/kr/touroot/global/config/TestQueryDslConfig.java, backend/src/test/java/kr/touroot/tag/service/TagServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
- 여행기 삭제 및 수정 기능 쿼리를 QueryDSL로 작성
- DB Table alias ambiguous 문제 해결
=> [Fix] - JPQL 관련 alias ambiguous 예외 발생

backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
- 이미지 경로에 따라 영구 저장소 이동 여부를 분기 한다.
=> [Fix] - 여행기 수정 시 이미 업로드 된 사진을 처리하지 못하는 오류

frontend/src/components/pages/my/MyPage.tsx, frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.tsx, frontend/src/components/pages/my/MyTravelogues/MyTravelogues.tsx, frontend/src/components/pages/search/SearchPage.tsx, frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx, frontend/src/main.tsx, frontend/src/queries/useInfiniteMyTravelPlans.ts, frontend/src/queries/useInfiniteMyTravelogues.ts, frontend/src/queries/useInfiniteSearchTravelogues.ts, frontend/src/queries/usePutTravelPlan.ts
여행 계획 수정, 마이페이지, 검색 페이지 → 리버
- 마이페이지
- 닉네임 수정
- 네트워크 오류 : 런타임에러 없이 걍 원래 닉넴으로 돌아감 (isPaused에 대한 처리 안함)
- 서버 오류 : 서버에 문제 발생 alert 잘뜨고 원래 화면으로 돌아감
- 로딩 중 : 빈화면 보이는 경우 없음
- 내 정보 불러오기
- 네트워크 오류 : → 이 상황 만드는게 더 힘들다, 네트워크 오류는 내 여행 계획, 내여행기에도 해놔서 내 정보에 까지 해놓을 필요 없음.
- 서버 오류 :  서버 오류시  alert 뜬다.
- 로딩 중 : 스켈레톤 잘뜸
- 내 여행계획 불러오기
- 내 정보 불러오기 성공해야먄 get 요청을 보낸다. (enabled)
- 네트워크 오류 : isPaused 처리함
- 서버 오류 :  error있으면 alert(error.message)
- 로딩 중 : 스켈레톤 잘뜸
- 내 여행기 불러오기
- 내 정보 불러오기 성공해야먄 get 요청을 보낸다.  (enabled)
- 네트워크 오류 : isPaused 처리함
- 서버 오류 :  error있으면 alert(error.message)
- 로딩 중 : 스켈레톤 잘뜸
- 여행 계획 수정
- 네트워크 오류
- useGetTravelPlan의 isPaused는 따지지 않음. ( 마이 페이지에서 내정보 불러오기의 isPaused 분기처리하지 않음
- 수정 확인 버튼 눌렀을 때 , usePutTravelPlan의 isPaused가 true이면 alert창 뜨게함
- 서버 오류
- usePut, get :  alert 처리되있ㅇ믐
- 로딩 중 
- 스켈레톤 …
=> [Fix] - 여행 계획 수정, 마이페이지, 검색 페이지 에러 핸들링

frontend/src/styles/globalStyle.ts
- 폰트 import path 수정
local 지웠을 때 import path가 일치하기 때문에 404가 아닌 200으로 잘 불러오는 것을 확인 할 수 있습니다!
빌드 결과물에 폰트 파일 잘 추가되는 것 확인할 수 있습니다!
자세한 내용은 백로그 참고 부탁드립니다!
=> [Fix] - 다운로드 된 폰트를 불러오지 않는 문제 해결 

backend/build.gradle, backend/src/main/resources/application.yml, backend/src/main/resources/db/migration/mysql/V1__init.sql, backend/src/test/resources/application-test.yml
- flyway 의존성 추가
- dev, prod 파일 flyway 설정 및 기존 데이터와 호환 설정
=> [Feature] - DB 스키마 형상관리를 위한 Flyway 도입 BE

frontend/cypress/e2e/travelPlanRegister.cy.ts, frontend/package.json, frontend/src/components/common/Calendar/Calendar.styled.ts, frontend/src/components/common/Calendar/Calendar.tsx, frontend/src/components/common/GoogleMapView/GoogleMapView.constant.ts, frontend/src/components/common/GoogleMapView/GoogleMapView.tsx, frontend/src/components/common/GoogleMapView/GoogleMapView.util.ts, frontend/src/components/common/Input/Input.styled.ts, frontend/src/hooks/pages/useTravelPlanDays.ts, frontend/src/hooks/useGoogleMap.ts
- 지도 기본위치 서울로 고정
- 검색, 입력창 눌렀을 때 확대되지 않도록 변경
- 캘린더 ui 내 지난 날짜에 대한 ui 피드백을 제공하도록 변경(이전 달 보여지는 부분 제거 및 지난 날짜는 gray text로 변경)
x
- top button(스크롤을 많이 내렸을 때 최상단으로 이동)의 경우 팀원들과 이야기가 더 필요할거 같아 따로 작업하진 않았습니다.
- meta 태그에 user-scalable="no"로도 확대 하지 않을 수 있지만 이 경우 접근성 문제가 발생해서 이를 해결하기 위한 다른 방법들을 찾다가 Input의 font-size를 16px로 변경했습니다.
- GoogleMapView에 대한 전반적인 리팩터링을 추가적으로 진행했습니다. (custom hook 분리, util 함수 및 상수 분리)
- e2e 테스트를 msw 핸들러가 있는 상태로 실행하면 테스트 통과가 되지 않는 문제를 확인했습니다! (그래서 msw 핸들러를 제거한채로 테스트를 일단 진행해주세요 :))
- 이 pr에서 cypress 관련 로직이 추가되어있습니다,,, (it.only 제거)
=> [Feature] - 데모데이 피드백 반영(지니)

frontend/public/index.html, frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.constants.ts, frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.tsx, frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx, frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx, frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx, frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx, frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
- Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading 이슈 해결
- google map 관련 dns-prefetch 및 preconnect 설정 추가
x
- 추가적으로 marker 대신 AdvancedMarker 사용에 대한 warning도 발견되었지만, 이 경우 아직 해당 라이브러리에서 지원이 되지 않아 불안정한 컴포넌트를 사용할 바엔 아직 사용하지 않는 것이 맞다고 생각하는데 다른 분들의 의견은 어떠실까요? 레퍼런스는 아래 첨부해놓겠습니다!
https://github.com/JustFly1984/react-google-maps-api/issues/3250
=> [Feature] - 여행 계획 상세 페이지 성능 최적화

frontend/src/components/common/Accordion/AccordionRoot/AccordionRoot.styled.ts, frontend/src/components/common/Input/Input.stories.tsx, frontend/src/components/common/Input/Input.styled.ts, frontend/src/components/common/Input/Input.tsx, frontend/src/components/pages/my/MyPage.styled.ts, frontend/src/components/pages/my/MyPage.tsx, frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.styled.ts, frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx, frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx, frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts, frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx, frontend/src/components/pages/travelogueEdit/TravelogueEditPage.styled.ts, frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.styled.ts, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
- 여행기 등록 & 수정 페이지 일자 추가하기 버튼과 등록, 수정 버튼 사이 발생하는 Layout Shift 해결
- 여행 계획 등록 & 수정 페이지 일자 추가하기 버튼과 등록, 수정 버튼 사이 발생하는 Layout Shift 해결
- 여행기
수정전
https://github.com/user-attachments/assets/70af768b-df98-4ce3-8f1c-68f53227ad8a
수정후
https://github.com/user-attachments/assets/e64206e8-4905-47b3-93e3-22683de45f30
- 여행 계획
수정전
https://github.com/user-attachments/assets/1cc96dc8-415c-476c-809a-919f93910c50
수정후
https://github.com/user-attachments/assets/cfc35930-7730-4a34-b47c-091eae76b992
input의 경우에도 count가 있는 경우 미리 값을 차지하도록 수정하였습니다 :)
=> [Feature] - Layout Shift 개선

frontend/src/components/common/GoogleMapView/GoogleMapView.tsx, frontend/src/hooks/useGoogleMap.ts
- 상세보기에서 좋아요 누를 때마다 지도 움직이는 문제 해결
- 사용자가 지도를 확대하지 못하는 문제 해결
- 여행 장소가 1개일 때 zoom level 9로 변경
x
- 한번 크로스 체킹해주시면 감사드리겠습니다~!
=> [Fix] - 상세보기에서 좋아요 누를 때마다 지도 움직이는 문제 & 사용자가 지도를 확대하지 못하는 문제 해결

backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java, backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
- 여행기 수정 시 썸네일을 임시 저장소에서 영구 저장소로 복사하도록 수정
=> [Fix] - 여행기 수정 시 썸네일을 임시 저장소에만 저장하는 버그 수정

backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java, backend/src/main/java/kr/touroot/global/logging/LoggingFilter.java
-  health checker api 로깅 필터 안거치게 변경
=> [Feature] - health checker api 로깅 필터 안거치게 변경

backend/src/main/java/kr/touroot/global/config/WebConfig.java
=> [Feature] - CORS 설정에서 exposeHeader 추가

frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx, frontend/src/hooks/pages/useTravelPlanDays.ts, frontend/src/hooks/pages/useTravelPlanForm.ts, frontend/src/hooks/pages/useTravelogueDays.ts, frontend/src/queries/usePostTravelogue.ts, frontend/src/queries/usePutTravelogue.ts, frontend/src/types/domain/travelTransform.ts, frontend/src/types/domain/travelogue.ts, frontend/src/utils/getDaysAndNights.ts, frontend/src/utils/getInitialTravelTitle.ts, frontend/src/utils/queryFunction.ts
- useTravelogueDays 로직 구조 개선
- useTravelPlanDays 로직 구조 개선
- query(usePostTravelogue, usePutTravelogue) 구조 개선 
x
- 타입 변경한 부분(TraveloguePayload, TravelTransformDays) 있으니 참고부탁드려요!
=> [Feature] - Immer을 사용한 코드 구조 개선 

backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java, backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlaceTodo.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java, backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanDayRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/request/PlanRequest.java, backend/src/main/java/kr/touroot/travelplan/dto/response/PlanCreateResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/PlanDayResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceResponse.java, backend/src/main/java/kr/touroot/travelplan/dto/response/PlanResponse.java, backend/src/main/java/kr/touroot/travelplan/repository/PlaceTodoRepository.java, backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanDayRepository.java, backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanPlaceRepository.java, backend/src/main/java/kr/touroot/travelplan/service/TravelPlanFacadeService.java, backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java, backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java, backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanDayTest.java, backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java, backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java, backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java, backend/src/test/java/kr/touroot/travelplan/service/TravelPlanFacadeServiceTest.java, backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
-  여행계획 생성 로직 양방향 연관관계 이용, 개선
- 여행계획 상세 조회 로직 양방향 연관관계 이용, 개선
- 여행계획 삭제 로직 양방향 연관관계 이용, 개선
- TravelPlanFacade가 작성되었습니다.
- 도메인을 다루는 계층을 하위 서비스로, DTO와 밀접하며 비즈니스 파사드를 관장하는 계층을 Facade 서비스로 나누었어요.
- 다만 그 의미가 미약해지고 있습니다 (by 양방향 연관관계)
- 우선은 여행기 도메인과의 통일성을 위해 진행된 작업으로 이해해주세요~
=> [Refactor] - 여행 계획 Service 코드 리팩터링

frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.tsx
=> [Fix] - 지도 장소명이 한국말이 아닌 영어로 나오는 이슈

backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java, backend/src/main/java/kr/touroot/travelogue/domain/search/SearchCondition.java, backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueSearchRequest.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java, backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
- 검색 + 필터링 API 통합
- 프론트 측과의 API 싱크를 맞추기 위해 `/search` 엔드포인트와 관련된 메서드를 살려뒀습니다. 대신 테스트는 전부 통합된 메서드로 변경해둬 삭제 결정되면 바로 삭제될 수 있게 처리해뒀습니다.
- 슬랙에 올렸던 정렬이 충돌나는 문제에 대해서도 일단은 `sort` 파라미터로 들어온 정렬이 후순위로 적용되게 해두었습니다. 다만 이것도 변경 요청 시 기존 정렬을 모두 제거하는 식으로 금방 처리할 수 있을 것 같아요.
위의 두 참고사항에 대해서 어떤 처리가 나을지 의견 남겨주세요~ 
슬랙에서도 얘기 나왔지만 여기에 제대로 의사결정 과정 기록해두면 좋을 것 같습니다. 👍
=> [Feature] - 검색 + 필터링 API 통합

frontend/src/components/common/Tab/Tab.styled.ts, frontend/src/components/pages/my/MyLikes/MyLikes.styled.ts, frontend/src/components/pages/my/MyLikes/MyLikes.tsx, frontend/src/components/pages/my/MyPage.styled.ts, frontend/src/components/pages/my/MyPage.tsx, frontend/src/components/pages/my/MyPageTabContent/MyPageTabContent.styled.ts, frontend/src/components/pages/my/MyPageTabContent/MyPageTabContent.tsx, frontend/src/components/pages/my/MyTravelogues/MyTravelogues.styled.ts, frontend/src/components/pages/my/MyTravelogues/MyTravelogues.tsx, frontend/src/components/pages/my/constants.ts, frontend/src/components/pages/search/TravelogueList/EmptySearchResult.tsx, frontend/src/components/pages/search/TravelogueList/TravelogueList.tsx, frontend/src/components/pages/search/constants.ts, frontend/src/constants/endpoint.ts, frontend/src/constants/queryKey.ts, frontend/src/queries/useDeleteUpdateHeart.ts, frontend/src/queries/useInfiniteMyLikes.ts, frontend/src/queries/usePostUpdateHeart.ts, frontend/src/types/domain/travelogue.ts
- 마이페이지 좋아요 탭 기능 구현
- 검색 창 국가 탭 기능 구현
현재 검색 창에서 존재하지 않는 국가를 검색하고 국가 탭을 누르면 오류를 던지는 상황이 발생합니다. 이를 백엔드 측과 논의한 끝에 다른 탭과 동일하게 없는 경우에도 그대로 없는 데이터를 던지도록 상호 합의 하였습니다 그래서 작동시 오류가 뜰 수 있는 점 감안해주시면 감사하겠습니다
=> [Feature] - 마이페이지 좋아요 탭 및 검색 창 국가 탭 기능 구현

frontend/src/components/common/Carousel/Carousel.styled.ts, frontend/src/components/common/Carousel/Carousel.tsx, frontend/src/components/common/Checkbox/Checkbox.styled.ts, frontend/src/components/common/Checkbox/Checkbox.tsx, frontend/src/components/common/Dropdown/Dropdown.styled.ts, frontend/src/components/common/Modal/DeleteModal/DeleteModal.tsx, frontend/src/components/common/Tab/Tab.styled.ts, frontend/src/components/common/Tab/Tab.tsx, frontend/src/components/pages/my/MyPage.styled.ts, frontend/src/components/pages/my/MyPage.tsx, frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts, frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx, frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts, frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx, frontend/src/components/pages/travelogueDetail/Thumbnail/Thumbnail.tsx, frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts, frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx, frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.styled.ts, frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx, frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanStartDate.ts, frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanTitle.ts
- 여행기 상세페이지 접근성 개선
- 여행 계획 상세페이지 접근성 개선
- 여행기 상세페이지 접근성 점수
https://github.com/user-attachments/assets/d1aa81d1-b98d-4b3a-a362-8829b44ca9c8
- 여행 계획 상세페이지 접근성 점수
https://github.com/user-attachments/assets/f89fb333-9216-4147-8cc6-1cb580d51efc
작업 완료했습니다
체크박스 label 부분이 약간 아쉬운 거 같기도 해서 얘를 개선해볼까싶기도 합니다! 일단 접근성 둘다 90점 넘어서 괜찮은 거 같습니다
=> [Feature] - 여행기 및 여행 계획 상세페이지 접근성 개선

backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
- travelogue_country.count로 정렬하는 조건 삭제
=> [Fix] - 사용하지 않는 정렬 쿼리 삭제

frontend/src/components/common/Textarea/Textarea.styled.ts, frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.tsx, frontend/src/components/pages/search/SearchPage.tsx, frontend/src/constants/storage.ts
- 여행기를 들어갈 때 탭이 클릭되지 않는 이슈 해결
- 마이페이지 내 `여행기로 전환` 텍스트 수정
- text area 모바일에서 확대되는 문제 수정
x
x
=> [Fix] - 6차 데모데이 1차 QA(지니)

frontend/src/components/common/Checkbox/Checkbox.styled.ts, frontend/src/components/common/Chip/Chip.styled.ts, frontend/src/components/pages/main/MainPage.tsx, frontend/src/components/pages/my/MyLikes/MyLikes.tsx, frontend/src/components/pages/search/TravelogueList/TravelogueList.tsx, frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
- 체크박스 아이콘 보이지 않는 문제 해결
- 여행기 보러 가기 클릭시 루트 페이지로 이동하는 문제 해결
- 태그 에니메이션 자동 드레그 문제 해결
- 태그 에니메이션 최초의 위에 있다가 내려오는 문제 해결
- 태그 에니메이션 최초의 위에 있다가 내려오는 문제 해결
해당 문제의 경우 chip 내부의 animation때문에 발생하는 것으로 알게 되었습니다. 다만, 당최 이유는 모르겠네요. 애초에 에니메이션의 경우 아래에서 원래 위치로 등장하게 했으나 왜 검색 페이지로 갔다가 홈으로 돌아오면 원래 위치보다 위에 있다가 아래로 떨어지는지 잘 모르겠습니다. 
우선, 해당 부분 해결은 에니메이션을 반대로 적용했습니다. 위에서 원래위치로 등장하게 에니메이션을 적용하였고 이로인하여 해결할 수 있었습니다. 우선에 이렇게 동작하도록 하고 추후 해당 부분 개선을 고민해봐야겠습니다.
=> [Fix] - 6차 데모데이 1차 QA(시모)

frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx, frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx, frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx, frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
=> [Fix] - 뒤로가기 막기 제거

backend/build.gradle, backend/src/main/resources/application.yml, backend/src/main/resources/logback-spring.xml
- Prometheus 의존성 추가
- Grafana 설정 추가
- Loki 관련 Logback 설정 추가
=> [Feature] - Prometheus, Grafana, Loki 설정 추가

backend/src/main/java/kr/touroot/TourootApplication.java, backend/src/main/resources/application.yml, backend/src/main/resources/logback-spring.xml
- 프로덕션 모니터링 서버 구축
- logback-spring.xml 에서 jasypt 로 복호화 된 loki url을 받도록 스프링 초기화 동작 재정의
- SSL 인증서 적용
=> [Feature] - 프로덕션 모니터링 구축

backend/build.gradle, backend/src/main/java/kr/touroot/global/config/CacheConfig.java, backend/src/main/java/kr/touroot/tag/cache/CacheConfig.java, backend/src/main/resources/application.yml, backend/src/test/java/kr/touroot/global/AbstractIntegrationTest.java
- application.yml에 Redis 연결 정보 추가
- Redis Config 작성
- CacheManager Redis로 변경
- Testcontainers Redis 추가
S3처럼 local에서 EmbeddedRedis를 사용할까 했는데 다음을 이유로 그러지 않기로 했습니다.
- 공식 라이브러리가 아닌 개인 소유의 라이브러리를 사용해야 함 (신뢰성 낮음)
- 라이브러리 노후화 (최신 업데이트가 6년전 ㄷㄷ redis 2.X 버전까지만 기능 업데이트)
- 불친절한 예외 메시지등 낮은 사용성
우선은 local 프로파일로 서버를 돌려보고 싶으시다면 redis를 실행하고 사용하시면 됩니다~
테스트의 경우에는Testcontainers를 통한 통합테스트 추상 클래스에 redis 컨테이너를 추가했으니 신경쓰지 않으셔도 됩니다.
=> [Feature] - Redis cache 도입

.github/workflows/be-cd-dev.yml, backend/src/main/resources/application.yml
- 프로덕션에 대한 모니터링 및 로깅 수집을 dev 서버로 통합
- 그라파나, 프로메테우스, 로키를 통합해서 하나만 사용하도록 변경
- 로키에서 로그 수집 시 호스트네임을 통해 prod와 dev 를 구분하도로록 설정
- 443 포트 하나로 dev와 그라파나를 포워딩 하도록 ngnix 구축
- dev 프로파일 톰캣에서 ssl 제거
그라파나, 프로메테우스, 로키를 2개로 쪼개서 관리할 필요가 없다고 느껴져 하나로 통합하였습니다.
그라파나에서 각각을 따로 보게 하려면 조금 더 설정을 해야합니다.
dev 프로파일에서 ssl 을 제거하였습니다.
ngnix에서 ssl termination 을 하도록 설정하고, 서브 도메인(`api-dev`, `grafana`) 에 따라 프록시 패스를 하도록 설정하였습니다.
이전 데이터까지 옮기고 약간의 설정만 더 하면 끝나지만, PR 먼저 오픈합니다.
현재 그라파나에서 prod/dev 로그가 섞여있는데, 설정을 통해 분리할 예정이니 참고해주세요.
코드와 관련된 부분은 추가 수정이 없을 것 같으니 확인해 주시면 감사하겠습니다.
=> [Feature] - 모니터링/로깅 시스템 통합

backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
레디스 동작도 애플리케이션 동작으로서 검증되어야 한다고 판단하여 테스트 코드 작성했습니다.
=> [Feature] - 레디스 관련 테스트 코드 작성

backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepository.java, backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImpl.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java, backend/src/test/java/kr/touroot/global/AbstractRepositoryIntegrationTest.java, backend/src/test/java/kr/touroot/global/config/TestQueryDslConfig.java, backend/src/test/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImplTest.java, backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
https://github.com/woowacourse-teams/2024-touroot/issues/643
임계치의 좋아요 개수를 계산하고 해당 값보다 높은 여행기의 좋아요수가 수정될 경우 page 캐시를 무효화하도록 로직을 작성했습니다.
SpEL에서 프록시의 실 객체 인스턴스 메서드를 참조하는 데에 어려움이 있어 캐시를 process하는 과정을 FacadeService에 위치시켰습니다.
=> [Feature] - 인기 여행기 페이징 응답 캐싱 무효화 전략 개선

backend/src/main/resources/application.yml, backend/src/test/resources/application-test.yml
현재 JPA 연관관계로 인해 데이터를 가져올 때 SELECT한 row 수 만큼 추가 쿼리가 발생하는 N+1문제가 발생합니다.
연관된 객체를 가져올 때 batch_size만큼 가져오도록 설정하여 N+1문제를 완화할 수 있습니다.
default_batch_fetch_size를 적용하여 한번에 100개씩 IN절을 활용하여 가져오도록 최적화 되었습니다.
Jmeter 테스트 시나리오 
- 조회 대상 여행기: 2박 3일 여행기 (각 날짜는 3개의 장소 지정)
- thread: 100
- duration: 200
- avg: 41
- avg: 30
<details>
<summary>발생 쿼리 비교</summary>
```sql
Hibernate: 
select
t1_0.id,
t1_0.author_id,
t1_0.created_at,
t1_0.deleted_at,
t1_0.like_count,
t1_0.modified_at,
t1_0.thumbnail,
t1_0.title 
from
travelogue t1_0 
where
t1_0.id=? 
and (
t1_0.deleted_at IS NULL
)
Hibernate: 
select
tt1_0.id,
tt1_0.tag_id,
tt1_0.travelogue_id 
from
travelogue_tag tt1_0 
where
tt1_0.travelogue_id=?
Hibernate: 
select
m1_0.id,
m1_0.created_at,
m1_0.deleted_at,
m1_0.email,
m1_0.kakao_id,
m1_0.login_type, …
```
=> [Feature] - default_batch_fetch_size 적용

backend/src/main/java/kr/touroot/global/config/SchedulingConfig.java, backend/src/main/java/kr/touroot/travelogue/repository/TravelogueRepository.java, backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeSyncService.java, backend/src/test/java/kr/touroot/global/AbstractRepositoryIntegrationTest.java, backend/src/test/java/kr/touroot/travelogue/repository/TravelogueRepositoryTest.java
다양한 방식이 있었지만 좋아요 충돌이 자주 일어나지 않는 현재 상황과 성능을 고려하여 배치 작업을 스케줄링하였습니다.
트래픽이 가장 적은 월요일 오전 3시 마다 여행기 좋아요 개수를 동기화하도록 설정하였습니다. 
현재 정의된 작업은 모든 여행기를 순회하며 일관성을 맞추는 작업을 수행합니다.
포스팅의 개수가 아직 많지 않아 이정도로 처리해도 성능에 크게 문제가 없는 것을 확인했는데, 후에 포스팅이 많아지면 modifiedAt을 활용하고 배치 단위 설정 및 병렬 처리를 고려해볼 수 있을 듯 합니다.
아직까지는 그 정도의 확장성을 고려하기 과하다 생각하여 현재수준으로 작업 마치고 PR올립니다.
https://github.com/woowacourse-teams/2024-touroot/issues/650
=> [Fix] - 서로 다른 테이블에 중복 저장되는 여행기 좋아요 정보 궁극적 일관성 확보
