frontend/.eslintrc.cjs
frontend/.gitignore
frontend/.prettierrc.json
frontend/package.json
frontend/public/index.html
frontend/src/App.tsx
frontend/src/main.tsx
frontend/src/styles/globalStyle.ts
frontend/tsconfig.json
frontend/webpack.common.js

[Feature] - 프로젝트 환경 세팅

---

backend/build.gradle
backend/src/main/java/woowacourse/touroot/global/config/SwaggerConfig.java

- `springdoc-openapi 2.6.0` 의존성 추가
- `SwaggerConfig` 작성

[Feature] - API 자동 문서화 사전 작업

---

.github/workflows/be-dev-ci.yml

[Feature] CI/CD Pipeline 구축

---

.github/workflows/be-dev-ci.yml

- Docker Push workflow 작성
- Docker Push workflow 작성

[Feature] - Docker Push / Docker Build CI workflow 추가

---

.github/workflows/be-dev-ci.yml

- docker image platform amd -> arm64 변경

[Fix] - CI workflow docker image platform 변경

---

backend/src/main/java/woowacourse/touroot/PingController.java

[Feature] - Ping api

---

backend/src/main/java/woowacourse/touroot/place/domain/Place.java
backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java
backend/src/main/java/woowacourse/touroot/travelogueday/domain/TravelogueDay.java
backend/src/main/java/woowacourse/touroot/traveloguephoto/domain/TraveloguePhoto.java
backend/src/main/java/woowacourse/touroot/travelogueplace/domain/TraveloguePlace.java

- Travelogue
- TravelogueDay
- TravelougePlace
- TravelougePhoto
- Place

feat: 여행기 관련 Entity 생성

---

backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java
backend/src/main/java/woowacourse/touroot/travelogueday/domain/TravelogueDay.java
backend/src/main/java/woowacourse/touroot/traveloguephoto/domain/TraveloguePhoto.java
backend/src/main/java/woowacourse/touroot/travelogueplace/domain/TraveloguePlace.java
backend/src/main/resources/application.yml

- DB 예약어와 같았던 Entity 필드명 및 DB 컬럼 이름 수정

[Fix] - Database 예약어였던 Entity 필드명 수정

---

backend/src/main/java/woowacourse/touroot/place/repository/PlaceRepository.java
backend/src/main/java/woowacourse/touroot/travelogue/repository/TravelogueRepository.java
backend/src/main/java/woowacourse/touroot/travelogueday/repository/TravelogueDayRepository.java
backend/src/main/java/woowacourse/touroot/traveloguephoto/repository/TraveloguePhotoRepository.java
backend/src/main/java/woowacourse/touroot/travelogueplace/repsitory/TraveloguePlaceRepository.java

- TravelogueRepository
- TravelogueDayRepository
- TravelougePlaceRepository
- TravelougePhotoRepository
- PlaceRepository

[Feature] - 여행기 관련 Entity Repository 생성

---

backend/src/main/java/woowacourse/touroot/place/domain/Place.java
backend/src/main/java/woowacourse/touroot/travelogue/dto/TravelogueResponse.java
backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueService.java
backend/src/main/java/woowacourse/touroot/travelogueday/dto/TravelogueDayResponse.java
backend/src/main/java/woowacourse/touroot/travelogueplace/dto/TraveloguePlaceResponse.java

[Feature] - 여행기 상세 조회 Service 생성

---

backend/Dockerfile
backend/src/main/resources/application.yml

- dev profile 분리
- ec2 instance 내부의 `touroot-docker.yml` file 수정

[Feature] - local/dev profile 분리

---

backend/src/main/java/woowacourse/touroot/travelogue/controller/TravelogueController.java

[Feature] - 여행기 상세 조회 Controller 생성

---

.github/workflows/be-dev-ci.yml

- Github Actions self-hosted runner 를 활용한 CD 구축

[Feature] - self hosted runner 를 활용한 CD 구축

---

.github/workflows/be-dev-ci-cd.yml

[Fix] - CD docker compose up 수행 경로 수정

---

backend/src/main/java/woowacourse/touroot/global/config/WebConfig.java

[Feature] - CORS 설정

---

.vscode/extensions.json
.vscode/settings.json
frontend/.stylelintrc.json
frontend/package.json

- stylelint 설정
- stylelint 관련 vscode 설정 추가
다른 분들도 해당 브랜치 들어가셔서 잘 되는지 한번 확인부탁드려요~!

[Feature] - stylelint 설정

---

.github/CODEOWNERS

[Feature] - codeowner 및 자동 할당 설정

---

.github/workflows/be-cd-dev.yml
.github/workflows/be-ci.yml
backend/src/main/resources/application.yml

- dev profile yml에 https 관련 설정 추가
- github action에 keystore.p12 생성 로직 추가

[Feature] - dev profile https

---

backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePhotoRequest.java
backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java
backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePlaceServiceTest.java

- 여행기 작성 요청 DTO의 필드 이름을 응답에 맞춰 변경

[Refactor] - 여행기 작성 요청 DTO 필드 이름 변경

---

backend/src/main/java/woowacourse/touroot/global/config/WebConfig.java

[Feature] - FE develop CORS 처리

---

backend/src/main/java/woowacourse/touroot/image/infrastructure/AwsS3Provider.java
backend/src/main/resources/application.yml
backend/src/test/resources/application-test.yml

- 기존에는 객체 url을 반환했으나 클라우드 프론트로 접속하는 이미지 url 을 반환하도록 수정

[Fix] - 이미지 저장 api 반환 값 변경

---

backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java
backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueTestFixture.java

- 여행기, 여행계획 DTO에 사용되는 도메인 용어 통일 개선

[Refactor] 여행기, 여행계획 DTO에 사용되는 도메인 용어 통일 개선

---

backend/src/main/resources/application.yml

- Kakao Redirect Uri 서버 엔드포인트에서 랜딩 페이지로 수정

[Fix] Kakao Redirect Uri 서버 엔드포인트에서 랜딩 페이지로 수정

---

backend/src/main/java/woowacourse/touroot/authentication/controller/LoginController.java
backend/src/main/resources/application.yml
backend/src/test/resources/application-test.yml

- 로그인 api HTTP METHOD 수정
- 카카오 로그인 redirect uri 랜딩 페이지로 수정

[Fix] Kakao Oauth 카카오 로그인 api 명세 수정

---

.github/workflows/be-cd-dev.yml
.github/workflows/be-ci.yml

- github action CI workflow gradle 캐싱
- github action CD workflow gradle 캐싱

[Feature] - Github action gradle 캐싱 도입

---

backend/src/main/resources/application.yml

[Feature] 카카오 로그인 Redirect Uri 프론트 배포 주소로 변경

---

backend/Dockerfile

- `Dockerfile`에서 빌드된 Spring Boot App 실행 시, KST로 실행되도록 변경.
- 프로덕션 코드에서도 설정할 수 있지만, 코드보단 해당 내용을 처리하는게 낫다고 생각했습니다.

[Fix] - Spring Boot Timezone KST로 설정

---

backend/src/main/java/woowacourse/touroot/image/domain/ImageFile.java

[Fix] - HEIC 이미지 파일 확장자 허용

---

.github/workflows/chromatic.yml

- 배포를 위한 chromatic.yml 파일 추가
x
- yml 파일이 사라져서 다시 추가해두었습니다!

[Feature] - chromatic 배포 yml 파일 추가

---

backend/src/main/resources/application.yml

- 프론트 로컬 개발을 위한 Oauth redirect uri 수정

[Feature] - 프론트 로컬 개발을 위한 Oauth redirect uri 수정

---

frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.styled.ts
frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.tsx
frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
frontend/src/components/common/Tab/Tab.styled.ts
frontend/src/components/pages/main/TravelogueCard/TravelogueCard.styled.ts
frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.styled.ts
frontend/yarn.lock

[Feature] - 3주차 스프린트 리팩토링

---

.github/workflows/frontend-ci.yml

- yml 내 의존성 설치 로직 수정
- yml 파일 수정해서 pull 받아주세용

[Fix] - ci 에러 해결

---

backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
backend/src/main/resources/application.yml

- SSL key-store-password 변경
- keystore 이슈로 삭제된 커밋 복구

[Fix] - SSL key-store-password 변경

---

frontend/package.json
frontend/src/apis/ApiError.ts
frontend/src/main.tsx
frontend/src/queries/useGetTravelogue.ts
frontend/yarn.lock

[Feature] - sentry 세팅하기

---

backend/.gitignore
backend/src/main/java/kr/touroot/global/config/WebConfig.java

- CORS config에서 allowedHeaders 제거
- gitignore에 keystore 추가

[Fix] - CORS config에서 allowedHeaders 제거

---

backend/src/main/resources/logback-spring.xml

- loggback console appender에 색상 추가

[Feature] - loggback console appender에 색상 추가

---

backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java

- 여행 계획 작성 에서 Insert 쿼리문 에러 해결

[Fix] - 여행계획이 저장되지 않는 문제 해결UUID

---

backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
backend/src/main/resources/application.yml

[Fix] - DB 커넥션 인코딩 파라미터 지정

---

backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
backend/src/main/resources/application.yml

[Fix] - 데이터베이스 url 원복

---

backend/src/main/java/kr/touroot/member/controller/MyPageController.java

[Feature] - 마이페이지 API Swagger 작업 

---

backend/src/main/java/kr/touroot/member/controller/MyPageController.java
backend/src/main/java/kr/touroot/member/dto/MyTravelogueResponse.java
backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java

[Feature] - 마이 페이지 내 여행 계획 응답 변경

---

frontend/src/components/common/Drawer/Drawer.tsx
frontend/src/contexts/DrawerProvider.tsx

- Drawer 열렸을 때, 뒤 컨텐츠 스크롤 안되도록 수정
https://github.com/user-attachments/assets/6d6bd8ba-0636-4415-a0ca-c3e5848302ed
수정 전 모습
위와 같이 스크롤바 생기는것이 안되도록 수정했습니다.
X

[Feature] - Drawer가 열려져있는 경우 화면 스크롤 안되도록 수정

---

backend/src/main/java/kr/touroot/global/config/WebConfig.java

- cors config에 `allowedMethods` 추가

[Fix] - 삭제 API CORS 문제 해결

---

backend/src/main/resources/application.yml

- 이미지 업로드 시 최대 용량을 5MB 에서 25MB 로 증가시킨다.

[Feature] - 이미지 업로드 용량 증가

---

frontend/package.json
frontend/src/main.tsx
frontend/webpack.common.js
frontend/yarn.lock

- sentry가 dev 환경에서만 동작하도록 변경
- 소스맵 관련 설정 추가
잘떠요~!

[Feature] - sentry 초기 설정 변경 & 소스맵 설정 추가

---

frontend/src/components/common/Dropdown/Dropdown.stories.tsx
frontend/src/components/common/Dropdown/Dropdown.tsx
frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
frontend/src/components/common/FloatingButton/FloatingButton.tsx
frontend/src/components/common/Header/Header.tsx
frontend/src/components/pages/login/KakaoCallbackPage.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
frontend/src/queries/useDeleteTravelPlan.ts
frontend/src/queries/useDeleteTravelogue.ts
frontend/src/queries/usePostTravelPlan.ts
frontend/src/queries/usePostTravelogue.ts
frontend/src/types/domain/travelogue.ts
frontend/src/types/domain/user.ts

- 여행 계획 및 여행기 상세 내 더보기 버튼에 등장하는 드롭다운 바깥에서 눌렀을 때 닫히지 않는 문제 해결
- 좋아요 버튼 기능이 작동하지 않음에도 불구하고 존재하는 문제 해결
- 다른 사람들이 여행 계획 페이지 들어갔을 때, 공유 & 더보기 버튼 보이는 문제 해결
- 플로팅 버튼에 공유하기 버튼이 존재하는 문제 해결
- 여행 계획 및 여행기 상세 내 더보기 버튼에 등장하는 드롭다운 바깥에서 눌렀을 때 닫히지 않는 문제 해결
https://github.com/user-attachments/assets/5cd6706d-ca82-40a9-8c95-281ce9f6bd0d
- 좋아요 버튼 기능이 작동하지 않음에도 불구하고 존재하는 문제 해결
- 플로팅 버튼에 공유하기 버튼이 존재하는 문제 해결
- 다른 사람들이 여행 계획 페이지 들어갔을 때, 공유 & 더보기 버튼 보이는 문제 해결
코드 구현은 완료! swagger 업데이트에 따라 정상 작동하는지 확인해 볼 예정

[Fix] - 3차 스프린트 QA 반영(시모) 

---

frontend/package.json
frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
frontend/src/main.tsx
frontend/yarn.lock

- GA4 기초 세팅
- 핵심 기능인 전환 버튼 클릭 이벤트에 대해서 집계하도록 수정

[Feature] - 배포한 서비스를 모니터링 하는 도구 GA 세팅 

---

backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java
backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java

- 여행기 작성 DTO에 Bean Validation 추가
- 테스트 코드 수정

[Fix] - 이미지 최대 업로드 개수 검증 누락 해결

---

frontend/src/components/common/Calendar/Calendar.tsx
frontend/src/components/common/Carousel/Carousel.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx

- TravelPlanTabContent 내 box의 key를 placeName이 아닌 id값(고유한 값)으로 변경
- 잘못된 key prop(Calendar, Carousel, TravelogueTabContent) 수정
https://github.com/user-attachments/assets/88001d7c-64b7-49ce-a799-25680aaba47d
x

[Fix] - 한 Day 내 중복된 장소 이름이 존재할 경우 게시물이 지속적으로 생기는 문제 해결

---

frontend/src/components/common/AvatarCircle/AvatarCircle.styled.ts
frontend/src/components/common/Header/Header.styled.ts
frontend/src/components/common/Header/Header.tsx

- 마이페이지에서 제 프로필 사진이 납작해지는것 수정
- 마이페이지 버튼에서 옆의 공백을 누르면 이동하지만, 상단과 하단의 공백을 누를 땐 이동하지 않는것 수정
- “홈"을 드로어에 포함 (누르면 메인페이지로 이동해야한다)

[Fix] - 3차 스프린트 QA 반영 2차 (리버) 

---

frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts
frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
frontend/src/queries/useDeleteTravelPlan.ts
frontend/src/queries/useDeleteTravelogue.ts
frontend/src/queries/useGetTravelogue.ts

- 여행 계획 삭제 후 이전 페이지로 돌아가면 삭제한 거 남아있는 문제 해결(캐싱 무효화가 이루어지지 않음)
- 바텀시트 열린 경우 화살표 마진 탑이 적어 답답해 보이는 문제 해결
- 존재하지 않는 여행기/여행 계획 페이지로 들어가면 아무것도 안 뜨는 문제 해결
- 여행 계획 삭제 후 이전 페이지로 돌아가면 삭제한 거 남아있는 문제 해결
https://github.com/user-attachments/assets/c4d19048-df2f-4156-b366-7ee0b1cd6101
- 바텀시트 열린 경우 화살표 마진 탑이 적어 답답해 보이는 문제 해결
해결 전
해결 후
- 존재하지 않는 여행기/여행 계획 페이지로 들어가면 아무것도 안 뜨는 문제 해결
https://github.com/user-attachments/assets/a35f1dfb-5631-4761-853a-fd08cb828fbd
컴포넌트 재사용하고 불 필요한 css 제거하다보니 의외로 바텀시트가 오래 걸렸네요 코드 참고 바랍니다!

[Fix] - 3차 스프린트 QA 반영 2차 (시모)

---

frontend/public/index.html
frontend/src/components/common/Box/Box.tsx
frontend/src/components/common/Calendar/Calendar.tsx
frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
frontend/src/constants/errorMessage.ts

- 지도 내 마커 위 순서 표시 텍스트 추가
- 사진 10장 넘게 올라가는 문제 해결
- 캘린더 모바일 hover 및 밑줄이 발생하는 문제 해결
- 여행 계획 상세 페이지 내 description 추가
- 여행 계획 상세 페이지 내 마지막 요소가 바텀 시트로 인해 보여지지 않는 문제 해결

[Fix] - 3차 스프린트 QA 반영 2차 (지니)

---

frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx

- 마커 색상 변경
- 여행기 상세 페이지 title & subtitle 순서 변경
x

refactor: 마커 색상 변경 & 여행기 상세 페이지 title & subtitle 순서 변경

---

backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
backend/src/main/java/kr/touroot/global/exception/S3UploadException.java
backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
backend/src/test/java/kr/touroot/image/infrastructure/AwsS3ProviderTest.java

[Fix] - S3 이미지 오류 예외 메시지 변경

---

backend/src/main/java/kr/touroot/authentication/infrastructure/KakaoOauthClient.java

- 카카오 서버와 통신 시 요청/응답 로깅
현재는 가장 나이브한 방식으로 구현했지만, 이후 다른 외부 API와 통신이 추가된다면 인터셉터를 이용해서 로깅을 한 곳에 통합해도 좋을 것 같습니다.

[Feature] - 외부 API request/response 로깅

---

backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueDayRequest.java
backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java

- 여행기 작성 시 요청 DTO 제약 조건 수정
- 변경된 여행기 작성 제약 조건에 따른 테스트 작성

[Fix] - 여행 날짜가 하나도 추가되지 않은 여행기가 정상 작성되버리는 문제 발생

---

backend/src/main/java/kr/touroot/member/repository/MemberRepository.java
backend/src/main/java/kr/touroot/member/service/MemberService.java

- 메소드 반환 타입 구체화
- 메소드 이름 오타 수정

[Fix] - 코드 오타 및 적절하지 않은 객체 타입 수정

---

backend/src/main/java/kr/touroot/authentication/controller/LoginController.java
backend/src/main/java/kr/touroot/authentication/dto/request/TokenReissueRequest.java
backend/src/main/java/kr/touroot/authentication/dto/response/LoginResponse.java
backend/src/main/java/kr/touroot/authentication/dto/response/TokenResponse.java
backend/src/main/java/kr/touroot/authentication/infrastructure/JwtTokenProvider.java
backend/src/main/java/kr/touroot/authentication/service/LoginService.java
backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
backend/src/main/resources/application.yml
backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
backend/src/test/java/kr/touroot/authentication/helper/LoginTestHelper.java
backend/src/test/java/kr/touroot/authentication/infrastructure/JwtTokenProviderTest.java
backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
backend/src/test/resources/application-test.yml

- 로그인 response에 refresh token 추가
- refresh token을 사용한 access token 재발급 기능 추가

[Feature] - refresh token 개발

---

frontend/src/apis/interceptor.ts
frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx

- 만료된 토큰 에러 발생시 interceptor 내에서 error를 throw하지 않고 early return 하도록 변경
- onSuccess callback 내 구조 분해 할당 제거

[Fix] - 만료된 access token 핸들링

---

backend/src/main/java/kr/touroot/tag/controller/TagController.java
backend/src/main/java/kr/touroot/tag/dto/TagResponse.java
backend/src/main/java/kr/touroot/travelogue/domain/TravelogueTag.java
backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueSimpleResponse.java
backend/src/main/java/kr/touroot/travelogue/repository/TravelogueTagRepository.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
backend/src/test/java/kr/touroot/tag/fixture/TagFixture.java
backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java

- 여행기 작성 시 태그 추가
- 여행기 조회 시 태그 추가
태그가 필수 값이 아니라서 분기가 생기는 바람에 코드가 많이 더러워졌습니다 😢
이를 해결하기 위해서 **차라리 `TravelogueTagService`가 `Optional`을 주는게 나을지에 대해 고민 중**인데 의견 주시면 감사하겠습니다리 🙇

[Feature] - 여행기 작성/조회 시 태그 추가

---

frontend/src/components/common/Input/Input.stories.tsx
frontend/src/components/common/Input/Input.styled.ts
frontend/src/components/common/Input/Input.tsx
frontend/src/components/common/Input/Input.type.ts

[Feature] - Input 컴포넌트 리팩토링

---

frontend/src/components/common/Icon/Icon.stories.tsx
frontend/src/components/common/IconButton/IconButton.stories.tsx

- Icon storybook에서 iconType option이 적용되도록 수정했습니다.
- Icon Button storybook에서 iconType option이 적용되도록 수정했습니다.
스토리북 확인 부탁드립니다~

[Fix] - Icon, Icon Button storybook에서 iconType option 적용되도록 수정

---

backend/src/main/java/kr/touroot/global/config/EmbeddedS3Config.java

[Fix] bean 중복 오류 수정

---

backend/src/main/java/kr/touroot/global/config/WebConfig.java
backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
backend/src/main/resources/application.yml
backend/src/test/resources/application-test.yml

- Prod CORS 허용
- 태그 필터링 정렬 순서 변경

[Fix] - Prod CORS 허용 및 태그 필터링 정렬 순서 변경

---

backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java

- 여행기 장소 사진 List not null 검증 추가
- 썸네일 String not blank 검증 추가

[Feature] - 엔티티 필수값 명세 재정의

---

backend/src/main/java/kr/touroot/global/config/AwsS3Config.java
backend/src/main/resources/application.yml

- S3 image base url Profile 별로 분리
- S3Client Bean 생성 Profile 별로 분리

[Fix] - S3 image base url Profile 별로 분리

---

frontend/__tests__/travelPlanRegisterPage.test.tsx
frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.tsx
frontend/src/components/pages/main/MainPage.styled.ts
frontend/src/components/pages/main/MainPage.tsx
frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.styled.ts
frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
frontend/src/constants/errorMessage.ts
frontend/src/hooks/pages/useTravelPlanDays.ts
frontend/src/hooks/pages/useTravelogueDays.ts
frontend/src/queries/useInfiniteTravelogues.ts

- 여행기 1개일 때 메인 페이지 스타일 깨지는 문제 해결
- 전환 버튼 전체 눌렀을 때 접히도록 수정.
- 내가 작성한 여행기를 여행계획 바텀시트 안보이게 수정
- 여행 계획 20자로 해서 올리면 마이페이지에서 이상하게 보여지는 문제 해결
- to do, 장소 사진, 장소 설명 보낼 때 빈 값의 경우 empty list 혹은 empty string로 보내기
- 서버 오류 및 네트워크 오류 에러 처리
- 여행기 1개일 때 메인 페이지 스타일 깨지는 문제 해결
- 전환 버튼 전체 눌렀을 때 접히도록 수정.
https://github.com/user-attachments/assets/61d32b63-c1a0-4c24-8932-c0a5a882a24e
- 내가 작성한 여행기를 여행계획 바텀시트 안보이게 수정
- 여행 계획 20자로 해서 올리면 마이페이지에서 이상하게 보여지는 문제 해결

[Fix] - 4차 스프린트 QA 반영 1차 (시모) 

---

backend/src/main/resources/application.yml

-  prod profile CORS allowedOrigins에 www 서브 도메인도 추가

[Feature] - prod profile CORS allowedOrigins에 www 서브 도메인 추가

---

backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
backend/src/main/resources/application.yml

[Feature] - 투룻 프로덕션 배포

---

backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java

- 여행기 썸네일이 유저로부터 입력되지 않은 경우 기본 이미지를 사용하지 못함

[Fix] - 여행기 썸네일이 유저로부터 입력되지 않은 경우 기본 이미지를 사용하지 못하는 오류 해결

---

frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
frontend/src/components/pages/travelogueRegister/TravelogueDayAccordion/TravelogueDayAccordion.tsx
frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
frontend/src/queries/useDeleteTravelPlan.ts
frontend/src/queries/usePostTravelPlan.ts
frontend/src/queries/usePostTravelogue.ts
frontend/src/queries/usePostUploadImages.ts

- 여행기 등록 & 수정, 여행 계획 등록, 여행 계획 상세 페이지 예외 및 로딩 처리
x
x

[Fix] - 여행기 등록 & 수정, 여행 계획 등록, 여행 계획 상세 페이지 예외 및 로딩 처리

---

frontend/src/components/common/Button/Button.styled.ts
frontend/src/components/common/Button/Button.tsx
frontend/src/components/common/Button/Button.type.ts
frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
frontend/src/components/common/FloatingButton/FloatingButton.tsx
frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.stories.tsx
frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlanDeleteModal/TravelPlanDeleteModal.styled.ts
frontend/src/components/pages/travelPlanDetail/TravelPlanDeleteModal/TravelPlanDeleteModal.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.styled.ts
frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.tsx
frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
frontend/src/constants/debouncedTime.ts
frontend/src/hooks/pages/useTravelPlanDays.ts

- 플로팅 버튼 글자 잘리는 문제
- 각 등록이나 수정 버튼 클릭 시 spinner 및 disabled 되도록 또 debounced 시간 늘리기
- 여행기에서 여행계획 전환시 todos 없는 문제

[Fix] - 4차 스프린트 QA 반영 2차 (시모)

---

frontend/src/components/common/Box/Box.styled.ts
frontend/src/components/common/Box/Box.tsx
frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.stories.tsx
frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.styled.ts
frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.tsx
frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
frontend/src/components/pages/search/SearchPage.styled.ts
frontend/src/components/pages/search/SearchPage.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
frontend/src/queries/useInfiniteSearchTravelogues.ts

- 여행계획에서도 상세지도 보기 추가
- 메인페이지에 타이틀 잘리는거
- 썸네일 올릴때 스피너 돌기
https://github.com/user-attachments/assets/324e306a-0df5-413e-9e0d-85a95bed8093
- 썸네일 스피너
- 메인 페이지 타이틀 안잘리기
-  여행계획에서도 상세지도 보기 추가
https://github.com/user-attachments/assets/e003af0e-6680-431c-adc0-205ebad488d5
- ThumbnailUpload 컴포넌트에 삭제 추가, 로딩 중일 때 스피너 추가

[Fix] - 4차 스프린트 QA 반영 2차 (리버)

---

frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
frontend/src/components/pages/my/MyPage.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
frontend/src/hooks/pages/useTravelPlanDays.ts
frontend/src/queries/usePostUpdateHeart.ts
frontend/src/utils/getDateRange.ts

- 구글맵 마커 클릭 하지 못하도록 변경
- 마이페이지 alert 2번 뜨는 현상 개선
- 여행기 - 여행 계획 변환 시 2일 이상 여행기에 대한 to do를 하나만 추가했을 때 등록이 안되는 문제 개선
- 로그아웃 된 상태에서 좋아요 누를 때 alert 2번 뜨는 문제 개선
- 여행 계획 시 dateRange가 하루씩 밀리는 문제 개선
- 달 마지막 일을 시작일로 할 때 여행 계획 Day 아코디언 추가 시 다음 달로 넘어가지 않는 문제 개선
- 여행 계획 등록 페이지 내 subText 추가
- 마이페이지 내 닉네임 수정 시 닉네임 한글로 입력 시 21자로 입력되는 문제 해결
- to do 입력 시 20자로 제한 하도록 변경
- 존재하지 않는 여행 계획 시 메인 페이지로 이동하도록 변경
- 여행기 수정 페이지 내 썸네일이 없을 경우 디폴트 이미지를 업로드 하도록 변경
x
x

[Fix] - 4차 스프린트 QA 반영 2차 (지니)

---

frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx

- 여행 계획 상세 페이지 내 작성자 아닌 게시물 접근 시 alert가 2번 뜨는 현상 개선
x
x

[Fix] - 여행 계획 상세 페이지 내 작성자 아닌 게시물 접근 시 alert가 2번 뜨는 현상 개선

---

frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.style.ts
frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.tsx
frontend/src/styles/tokens/typography.ts

- line height 수정
- shareModal 여행기 공유 -> 여행기 계획으로 텍스트 수정

[Fix] - line height,shareModal 수정

---

backend/src/main/java/kr/touroot/member/domain/Member.java
backend/src/main/java/kr/touroot/place/domain/Place.java
backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java

- 멤버 테이블 인덱스 명세 작성
- 여행 계획 테이블 인덱스 명세 작성
- 여행 장소 테이블 인덱스 명세 작성
ddl-auto가 create drop인경우 엔티티 명세에 따라 인덱스가 생성되지만 저희는 ddl auto 전략이 create drop이 아님으로 실제 인덱스 생성에 기여하지는 않습니다.
다만 엔티티의 명세로써 인덱스 내용이 드러나야 한다고 생각해 진행한 작업입니다!

[Feature] - 엔티티 테이블 인덱스 명세 작성

---

backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
backend/src/main/java/kr/touroot/travelogue/domain/TravelogueDay.java
backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java
backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java

- 여행기 관련 도메인 (여행 날짜, 여행 장소 등등..) 양방향 연관관계로 개선
- 여행 계획 관련 도메인 (여행 계획 날짜, 여행 계획 장소 등..) 양방향 연관관계로 개선
엔티티에 양방향 연관관계만 리스트로 열어두었습니다. 관련해서 개선할 수 있는 서비스 메서드 리팩토링은 이어지는 이슈에서 진행하겠습니다~

 [Refactor] - 역방향 참조 필요한 엔티티 양방향 연관관계로 개선 

---

backend/build.gradle
backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
backend/src/main/resources/application.yml

- Spring Actuator 의존성 추가
- Spring Actuator 보안을 위한 best practice property 추가
- Spring Actuator가 공개하는 정보는 `info`, `health`, `metrics`입니다.

[Feature] - Spring Actuator 도입

---

frontend/public/index.html

- kakao sdk script body 태그로 이동
이제 touroot-bundle 파일이 더 먼저 실행되는 것을 확인할 수 있음
자세한 내용은 백로그 참고부탁드려요~!

[Feature] - kakao bundle lazy loading 적용

---

backend/src/main/java/kr/touroot/authentication/service/LoginService.java
backend/src/main/java/kr/touroot/global/config/DataSourceConfig.java
backend/src/main/java/kr/touroot/global/config/DynamicRoutingDataSource.java
backend/src/main/java/kr/touroot/member/service/MemberService.java
backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
backend/src/main/resources/application.yml

- RDS reader, writer 엔드포인트 연결
- Transactional 설정에 따른 DatasourceDynamicRouting 구현
- 서비스 메서드 Transactional 속성 검토

[Refactor] - RDS reader, writer 엔드포인트 연결  쓰기 작업, 읽기 작업 분리 검토

---

backend/src/main/resources/db/migration/mysql/V2__delete_place.sql

[Fix] - Flyway Migration Fail 버그 해결 

---

frontend/webpack.common.js
frontend/webpack.production.js

- assets(image, font에 대한 contenthash 설정)
- 번들 파일에 대한 contenthash 설정 추가
x
- 자세한 내용은 백로그 참고 부탁드립니다!
- avif에 대한 설정을 추가했고, font와 이미지에 대한 설정을 분리했습니다.

[Feature] - webpack 캐시 버스팅 설정

---

frontend/package.json
frontend/src/components/common/Spinner/Spinner.tsx
frontend/src/components/common/index.ts
frontend/src/router.tsx
frontend/webpack.production.js
frontend/yarn.lock

- router 내 존재하는 page 컴포넌트들에 대한 코드 스플리팅 작업 진행
x
백로그에 before after 비교 결과 추가해두었습니다!

[Feature] - 코드 스플리팅 설정

---

frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
frontend/src/constants/errorMessage.ts
frontend/src/constants/resize.ts
frontend/src/utils/resizeAndConvertImage.ts

- 이미지 리사이즈를 한다.
- webp 이미지 포맷을 사용한다.
- 스샷 ㄱㄷ
X

[Feature] - 이미지 최적화

---

frontend/src/components/pages/main/MainPage.styled.ts

[Fix] - 테그 필터링 스크롤 끝까지 되지 않는 문제 해결

---

frontend/src/components/pages/search/SearchPage.styled.ts
frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx

- 검색 페이지 탭바 width 수정
- 여행기 수정페이지에서 이미지 최적화 안됨
X
X

[Fix] - 검색 페이지 탭바 width 수정, 여행기 수정페이지에서 이미지 최적화 안됨 

---

frontend/src/router.tsx

- SearchPage에 대한 lazy loading 제거
X
x

[Fix] - 검색 초기 페이지로 접근 시 에러가 발생하는 문제 수정

---

backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
backend/src/main/resources/application.yml
backend/src/test/resources/application-test.yml

[Fix] - develop S3 원본 경로 검증 url 변경

---

frontend/src/components/pages/notFound/NotFoundPage.tsx

- NotFound의 버튼 텍스트가 잘못된 부분 수정
**개선 결과**
- x

[Fix] - NotFound의 버튼 텍스트가 잘못된 부분 수정

---

backend/src/main/resources/db/migration/mysql/V5__delete_place_id_not_null_constraint.sql

- place_id NOT NULL 제약 조건 삭제되지 않아, 새로운 여행기를 생성하지 못하는 버그 있음
- 새로운 flyway 스크립트 통해 해결

[Fix] - place_id NOT NULL 제약 조건 삭제

---

backend/src/main/resources/db/migration/mysql/V5__delete_place_id_not_null_constraint.sql

[Feature] - 프로덕션 api-v1.1.1 배포

---

frontend/src/components/common/Header/Header.stories.tsx
frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
frontend/src/components/common/Modal/Modal.stories.tsx
frontend/src/components/pages/main/MainPage.constants.ts
frontend/src/components/pages/search/SearchPage.styled.ts
frontend/src/components/pages/search/SearchPage.tsx
frontend/src/components/pages/search/TravelogueList/TravelogueList.styled.ts
frontend/src/components/pages/search/TravelogueList/TravelogueList.tsx

- 검색창 placeholder 수정
- 검색 결과 페이지에서 헤더 border 안보임 + 탭 이상하게 보임
- 좋아요순, 최신순 띄워쓰기
X

[Fix] - 5차 스프린트 QA 반영 1차 (리버)

---

frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlanTodoItem/TravelPlanTodoItem.tsx
frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
frontend/src/hooks/pages/useTravelPlanDays.ts
frontend/src/mocks/data/travelPlan.json
frontend/src/queries/usePatchTravelPlanTodo.ts
frontend/src/queries/usePostTravelPlan.ts
frontend/src/queries/usePutTravelPlan.ts
frontend/src/types/domain/travelPlan.ts

- 여행기 수정 및 등록 응답 명세 통일
- 여행 계획 수정 및 등록 응답 명세 통일
- isChecked로 응답 명세 통일

[Refactor] - API 요청 및 응답 명세 통일

---

.github/workflows/be-cd-prod.yml

-  무중단 배포 관련 Shell Script 동작하도록 파이프라인 작성

[Feature] - 무중단 배포 반영 CI/CD 파이프라인 작성

---

.github/workflows/be-cd-prod.yml

[Feature] - 프로덕션 api-v1.1.3 배포

---

frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx

- 여행 계획 상세 페이지로 이동 시 scroll 최상단으로 이동 되도록 변경 
- 여행기 상세 페이지로 이동 시 scroll 최상단으로 이동 되도록 변경 
x
x

[Feature] - 여행 계획 & 여행기 상세 페이지로 이동 시 scroll 최상단으로 이동 되도록 변경 

---

backend/src/main/java/kr/touroot/travelogue/domain/TravelogueCountry.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueCountryService.java
backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueCountryFixture.java

- 엔티티의 `count` 컬럼 타입을 Integer로 변경

[Fix] - 스키마와 엔티티 사이의 컬럼 타입 불일치로 인한 버그 해결

---

backend/src/main/java/kr/touroot/travelogue/domain/search/CountryCode.java
backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepository.java
backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
backend/src/test/java/kr/touroot/travelogue/domain/search/CountryCodeTest.java

- 검색 쿼리 분기 계층 변경
- 없는 국가 예외 처리 삭제

[Feature] - 검색 쿼리 분기 계층 변경

---

frontend/src/router.tsx

- router 내 lazy loading 로직 제거
x
x

[Fix] - lazy loading 제거

---

frontend/src/apis/interceptor.ts
frontend/src/constants/errorMessage.ts

- 백엔드 내 던지는 예외 메시지가 2개인 이유로, 다른 예외 메시지 검증 로직 추가
x
x

[Fix] - 토큰 재발급이 제대로 동작하지 않는 오류 개선

---

frontend/src/components/common/Icon/Icon.styled.ts
frontend/src/components/common/TopButton/TopButton.styled.ts
frontend/src/components/common/TopButton/TopButton.tsx
frontend/src/components/pages/landing/FourthPage/FourthPage.styled.ts
frontend/src/components/pages/landing/LandingPage.tsx

[Fix] - 6차 데모데이 1차 QA(리버)

---

frontend/src/components/pages/landing/FirstPage/FirstPage.styled.ts
frontend/src/components/pages/travelPlanDetail/TravelPlanTodoItem/TravelPlanTodoItem.styled.ts

- 랜딩 페이지 페이지 잘리는 문제 
- todo 세로 배열이 맞지 않는 문제

[Fix] - 랜딩 페이지 페이지 잘리는 문제 및 todo 세로 배열이 맞지 않는 문제

---

frontend/src/components/pages/landing/FirstPage/FirstPage.styled.ts
frontend/src/components/pages/landing/FirstPage/FirstPage.tsx
frontend/src/components/pages/landing/LandingPage.styled.ts
frontend/src/components/pages/landing/LandingPage.tsx
frontend/src/components/pages/landing/SecondPage/SecondPage.styled.ts
frontend/src/components/pages/landing/SecondPage/SecondPage.tsx
frontend/src/components/pages/travelPlanDetail/TravelPlanTodoItem/TravelPlanTodoItem.styled.ts

- 랜딩페이지 화살표 위치 문제 해결
- 두번째 페이지 에니메이션 제거

[Fix] - 랜딩페이지 화살표 위치 문제 해결 및 두번째 페이지 에니메이션 문제 해결

---

frontend/package.json
frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
frontend/src/hooks/usePrompt.ts
frontend/src/utils/resizeAndConvertImage.ts
frontend/yarn.lock

- usePrompt, useBeforeUnload로 새로고침 및 뒤로가기 제어 (https://github.dev/remix-run/react-router)
- heic 이미지 문제 해결
x
x

[Fix] - 6차 데모데이 2차 QA(지니)

---

frontend/src/components/pages/main/MainPage.styled.ts

[Fix] - 6차 데모데이 전 2차 QA(시모)

---

frontend/src/hooks/useModalControl.ts
frontend/src/utils/resizeAndConvertImage.ts

[Fix] - 6차 데모데이 2차 QA(리버) 

---

backend/src/main/resources/logback-spring.xml

- dev, prod 에 로키 어펜더 추가
- local 에 로키 어펜더 제거

[Feature] - 로키 어펜더를 dev, prod 에서 동작하도록 변경

---

backend/src/main/resources/application.yml

[Feature] - S3 버킷 이름 변경

---

backend/src/main/resources/application.yml
backend/src/main/resources/logback-spring.xml

-  local용 loki url 제거
- Loki url application.yml에서 관리하게 변경
- prod profile Loki appender 제거

[Refactor] - logback에 작성된 Loki 설정 수정

---

backend/src/main/resources/application.yml

[Feature] - graceful shutdown 설정 추가

---

backend/src/main/java/kr/touroot/member/service/MemberService.java
backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java

- 멤버 닉네임 중복 검증 로직 제거
https://github.com/woowacourse-teams/2024-touroot/issues/616

[Feature] - 멤버 닉네임 중복을 허용

---

backend/src/main/resources/application.yml

https://github.com/woowacourse-teams/2024-touroot/issues/641

[Fix] - dev 환경 Redis host 수정

---

backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepository.java
backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImpl.java
backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
backend/src/test/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImplTest.java

좋아요 정보를 가져올 때 여행기 정보와 여행기 작성자 정보까지 fetch join하여 가져오도록 수정하였습니다. 
Jmeter 성능 측정
- 조회 시나리오: 내가 좋아요한 여행기들의 첫번째 페이지 조회 (5개의 여행기)
- thread: 100
- duration: 120sec
- avg: 31
- avg: 20
<details>
<summary>발생 쿼리 비교</summary>
```sql
Hibernate: 
select
m1_0.id,
m1_0.created_at,
m1_0.deleted_at,
m1_0.email,
m1_0.kakao_id,
m1_0.login_type,
m1_0.modified_at,
m1_0.nickname,
m1_0.password,
m1_0.profile_image_url 
from
member m1_0 
where
m1_0.id=?
Hibernate: 
select
tl1_0.id,
tl1_0.liker_id,
tl1_0.travelogue_id 
from
travelogue_like tl1_0 
where
tl1_0.liker_id=? 
order by
tl1_0.id desc 
limit
?, ?
Hibernate: 
select
count(tl1_0.id) 
from
travelogue_like tl1_0 
where
tl1_0.liker_id=?
Hibernate: 
select
t1_0.id,
t1_0.author_id,
t1_0.created_at,
t1_0.deleted_at,
t1_0.like_count,
t1_0.modified_at, …
```

[Feature] - TravelogueLike 조회를 fetch join으로 개선
